anufrievroman/waypaper

- waypaper/__main__.py
`--fill` option was expecting a True or False value, because it had the argument parse option of `action="store_true"`. So I just change it to only accept the options from the FILL_OPTIONS array.
> fix: --fill options wrong type

- waypaper/app.py
- waypaper/changer.py
The usage of swww init instead of swww-daemon was causing a deprecation warning to appear "DEPRECATION WARNING: `swww init` IS DEPRECATED. Call `swww-daemon` directly instead".
`swww init` was depricated in version 0.9.0 of swww but `swww-daemon` was added back in version 0.7.0.
This fixes issue #39
> fix: remove swww deprecation warning

- waypaper/changer.py
- waypaper/options.py
I added `hyprpaper` support using `hyprrctl`. I tested it with `--restore` flag and it restores the wallpapers properly. The `monitor` variable in `changer.py`  was locally changed to be an empty string if it was set to `All` so that `hyprpaper` would set it to all monitors correctly.
This fixes issue #7 .
> enhancement: Add hyprpaper backend support

- waypaper/app.py
- waypaper/changer.py
I noticed a bug where there was not enough of a delay when changing wallpapers for the first time when `hyprpaper` was not already running that caused the wallpapers to be preloaded and set when the `hyprpaper` daemon was not yet loaded. I fixed this by checking if the `hyprpaper` process is already running and if not  launch `hyprpaper` and put a 1 second delay to ensure that the wallpaper is set correctly.
This fixes an bug introduced in #45
> fix: hyprpaper first launch not setting wallpaper correctly

- waypaper/app.py
As mentioned in point 1 in this  [comment](https://github.com/anufrievroman/waypaper/issues/7#issuecomment-2119082510), the listing of monitors for `hyprland` needed to be independent of `sww` and `sww-daemon`. This pull request separates the querying for monitors for `hyprland` from `sww` and solely utilizes `hyprctl` to get the monitor names. This was done by calling `hyprctl monitors` and extracting the monitor names with the help of the standard library `re` module. A small rework for how the monitors combo-box  is displayed was done to avoid duplicating the function calls in the `hyprpaper` backend.
> enhancement: Add support for listing monitors in hyprland using hyprctl

- waypaper/changer.py
I fixed a bug where `hyprpaper` would unload wallpapers after being applied. In the majority of cases, the wallpaper would apply correctly in spite of them being unloaded from memory. However, larger wallpapers would be unloaded before being applied to the screen. The unload command worked as intended after the fix, it would drastically reduce the memory consumption of `hyprpaper` when viewing wallpapers in `waypaper` and effectively cap memory consumption instead of constantly growing as was happening before.
> fix: Hyprpaper would unload wallpaper before being applied.

- waypaper/changer.py
As mentioned in issue #7 , the wallpapers would sometimes not be preloaded before being set by hyprpaper. This PR fixes that by serializing the shell commends using the check_output function and it also retries up to 10 times to set the wallpaper in the off chance that it somehow fails to set the wallpaper (although since it is serialized it should never happen).
> fix: Consistantly set wallpaper using hyprpaper backend

- waypaper/app.py
Add the `ESC` key as a quit action additionally to the `q` option. 
Probably more common for non-vim users
> Quit the Appication with ESC

- waypaper/__main__.py
- waypaper/translations.py
This PR addresses the feature request in issue #55. It adds the command line option `--list` where the currently set wallpapers and their corresponding monitor in the form of a `JSON` string. The help text has been added to all of the languages in `translations.py` but are not translated in anything that is not English.
> Add listing of monitors and wallpapers through the command line option --list

- waypaper/__main__.py
- waypaper/app.py
I was annoyed when `waypaper --restore` only restored the image but not the settings used to display the image stored in `config.ini`, so I decided to fix that. That probably fits better with the expectations of what `--restore` is supposed to do.
> Have --restore argument actually restore the saved config

- waypaper/__main__.py
- waypaper/app.py
- waypaper/changer.py
- waypaper/common.py
- waypaper/config.py
This fixes the issue #73 
Config class currently doesn't encapsulate the properties such as `selected_wallpaper` and `wallpapers` properly. External calls change the state of the property and they do so inconsistently. Some will set them to plain strings others to `pathlib.Path` objects. The issue is that `Path` cannot be serialized automatically as a string, which makes saving config fragile and it breaks.
This change enforces a few things:
1. Config will always serialize to plain types (string/int) and deserialize opportunistically to Path objects where possible. The idea is that once the values are loaded and validated from the config the rest of the code doesn't have to worry. They are proper Path objects.
1. Fix up all the call patterns to use Path objects if possible. In some cases …
> Remove mixed use of Path/strings for file/folder locations from config

- README.md
In the Fedora install section it says "wayapaper" instead of "waypaper"
> Remove extra 'a' in wayapaper

- README.md
- setup.py
- waypaper/app.py
- waypaper/changer.py
- waypaper/options.py
Fix for #12.
Mpvpaper supports:
- fill types: fill, fit, stretch
- background color
- both video and image as wallpaper
- ~~multimonitor support~~
Notes:
Although mpvpaper itself supports multi-monitor support it is not implemented in waypaper yet. This is mainly because I couldn't understand why in `common.py:123` the `get_monitor_names()` is divided into two funtions, wouldn't it be better to use the same function and doesn't rely on either swww or hyprctl? Sorry if this is a stupid question but is there a reason to do so?
Also maybe for the same reason multi-monitor support is not implemented in swaybg although it supports it.
> Add mpvpaper support

- waypaper/app.py
- waypaper/changer.py
Enable multi-monitor support for swaybg and mpvpaper and also hide the monitor choice box in feh or wallutils.
Slight fix for #85
> Improve multi-monitor support

- waypaper/config.py
Initial proposal to fix #89 
I have on load of a state file set the `self.selected_monitor` in waypaper/config.py to the first index of the monitor list, not perfect, but without a routine to keep track of what monitors are being addressed per state-file, it's what I can do for now. 
I can look into or implement a different solution, upon request. But this currently works, to fix my bug. Further testing should be done to ensure this doesn't break anything else.
> Fixed Issue with CMD Support for Multi-Monitor using state files.

- waypaper/config.py
Even when setting `backend = none` in your config, the program refuses to start since it assumes it has detected at least 1 backend, which with the "none" backend would make it 2. "none" isn't really a backend though, and the code on `__init__` fails if no backends were detected before it has the chance to load the config.
> fix: config won't load if they're not backends detected

- waypaper/options.py
As mpvpaper supports both static and animated AVIF, I wanted to add it.
I'm too much of a skill issue to properly convert my videos to WEBP or GIF without losing quality or getting terrifying file sizes, so here I am.
Already tested, worky and thumbnail generation is hitchless.
Thank you for your time.
> Mark AVIF as supported by mpvpaper backend

- waypaper/common.py
I changed the function from glob.glob to pahtlib.Path.glob and use the argument that follows symlinks and filtered the files manually. Fixes #132.
> Fix bug by using glob function that follows symlinks.

- data/waypaper.desktop
I always forget the name of the app and this change helps me find it in [tofi](https://github.com/philj56/tofi).
Used `wallpapers` instead of `wallpaper` to be more forgiving to user input.
> Added a keyword to the desktop file to help with the search in dmenu's

- waypaper/__main__.py
- waypaper/app.py
- waypaper/options.py
this mostly addresses the issues raised in #120 and #163, without over-complicating things too much. 
this handles the exceptions caused by the upstream package a bit more gracefully. Instead of crashing right out of the gate, we swallow the exception and fallback to "All" as the default monitor option, regardless of backend.
When an exception is caught, a simple warning is printed with the exception message. 
you _could_ argue that this breaks multi-monitor support, but this will only happen in cases where the application is already crashing, so a net positive IMO 🙂 
Let me know if there's any questions!
> prevent crashing when screeninfo fails

- waypaper/app.py
Zero byte files cause file paths and file names to become mismatched in element length due to removing from the list in the middle of iteration. This will cause the image grid to have fewer images load than there are paths, and clicking on some images will actually set the background to the one next to the one you clicked on.
> Fix zero byte files bug

- waypaper/app.py
- waypaper/common.py
I noticed that images with the same file name in different subfolders would share thumbnail icons. To fix this, I made the filename of the thumbnail be the md5 hash of the real path of the image.
Opted for md5 hash instead of replacing "/" with "\_" (or similar approach) because that has issues with collisions for regular use of an "\_", and could run into path length issues.
I think there are many ways of solving this problem, feedback welcomed!
(also sneaking in a fix for symlinks within subdirectories causing None image names)
> Take hash of image path for cache path
